use anyhow::{Context, Result};
use std::os::unix::fs::PermissionsExt;
use std::path::PathBuf;

use crate::config::StatusSpec;
use crate::tmux;

fn segments_dir() -> Result<PathBuf> {
    let home = dirs::home_dir().context("no home directory")?;
    let dir = home.join(".sessionx").join("segments");
    std::fs::create_dir_all(&dir)?;
    Ok(dir)
}

/// Materialize a segment script idempotently. Returns its path.
fn write_segment(name: &str, command: &str) -> Result<PathBuf> {
    let dir = segments_dir()?;
    let path = dir.join(format!("{name}.sh"));
    let body = format!("#!/usr/bin/env bash\n# auto-generated by sessionx — do not edit\nset -e\n{command}\n");
    let needs_write = match std::fs::read_to_string(&path) {
        Ok(existing) => existing != body,
        Err(_) => true,
    };
    if needs_write {
        std::fs::write(&path, &body)?;
        let mut perm = std::fs::metadata(&path)?.permissions();
        perm.set_mode(0o755);
        std::fs::set_permissions(&path, perm)?;
    }
    Ok(path)
}

/// Apply the configured status bar to a session. Scope: per-session.
pub fn apply(session: &str, spec: &StatusSpec) -> Result<()> {
    if !spec.enabled {
        return Ok(());
    }

    // Materialize segment scripts first so format strings can reference them.
    for seg in &spec.segments {
        write_segment(&seg.name, &seg.command)?;
    }

    // Style options. Keys in the config use snake_case for ergonomics; tmux uses dashes.
    // Window/pane-scoped options must be applied per-window (set-window-option).
    for (k, v) in &spec.style {
        let key = k.replace('_', "-");
        if key.starts_with("window-") || key.starts_with("pane-") {
            tmux::set_window_option_for_all(session, &key, v)?;
        } else {
            tmux::set_option(session, &key, v)?;
        }
    }

    if let Some(left) = &spec.left {
        tmux::set_option(session, "status-left", left)?;
        // Default left-length is 10 — usually too short for custom segments.
        tmux::set_option(session, "status-left-length", "200")?;
    }
    if let Some(right) = &spec.right {
        tmux::set_option(session, "status-right", right)?;
        tmux::set_option(session, "status-right-length", "200")?;
    }
    if let Some(fmt) = &spec.window_format {
        tmux::set_window_option_for_all(session, "window-status-format", fmt)?;
    }
    if let Some(fmt) = &spec.current_window_format {
        tmux::set_window_option_for_all(session, "window-status-current-format", fmt)?;
    }
    if let Some(interval) = spec.status_interval {
        tmux::set_option(session, "status-interval", &interval.to_string())?;
    }

    Ok(())
}

/// Build SX_ICON_<NAME> env vars for hooks.
pub fn icon_env(spec: &StatusSpec) -> Vec<(String, String)> {
    spec.icons
        .iter()
        .map(|(k, v)| (format!("SX_ICON_{}", k.to_uppercase()), v.clone()))
        .collect()
}
